FROM alpine

# install openssh and borgbackup
RUN apk add --no-cache docker-cli openssh-server openssh-client borgbackup btrfs-progs losetup python3 py3-btrfs-progs bash grep py3-llfuse tzdata sudo

# dev only deps
RUN apk add --no-cache make py3-pip; pip install ipython

RUN ssh-keygen -A; adduser --disabled-password borg;
RUN mkdir /home/borg/.ssh; chown borg:borg /home/borg/.ssh; chmod 700 /home/borg/.ssh;

COPY config/authorized_keys /home/borg/.ssh/authorized_keys

RUN chown borg:borg /home/borg/.ssh/authorized_keys; chmod 600 /home/borg/.ssh/authorized_keys;

# Configure SSH server
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config \
  && echo "AllowUsers borg" >> /etc/ssh/sshd_config

# Allow login with ssh key only, set impossible password
# https://arlimus.github.io/articles/usepam/
RUN sed -i 's/borg:!:/borg:*:/' /etc/shadow

# copy s4 code into code directory
COPY . /code

# make sure s4 is installed
RUN make -C /code install

# create keys directory for any provided ssh keys
RUN mkdir -p /keys

WORKDIR /s4

ENTRYPOINT ["s4"]
