name: CI

on:
  push:
    branches:
      - '**' # This will run the workflow on every push to any branch

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build agent and target containers
      run: make docker

    - name: Run tests
      run: make test
